### ISSUE TITLE
Berserko not adding headers in Burp 2020.4

### ISSUE THREAD

**Issue by bshr** [nccgroup/Berserko#6]
Berserko doesn't seem to work in latest Burp - no headers are added, and the following exception appears in error output:
java.lang.ClassNotFoundException: com.sun.security.jgss.ExtendedGSSContext

**Comment by rtt-ncc** [comment]
Thanks for reporting this, I have been able to reproduce.
Looks like some Kerberos-related classes may have been removed again from the JRE shipped with Burp, as happened before - see https://github.com/nccgroup/Berserko/issues/5.
Investigating further now...

**Comment by rtt-ncc** [comment]
Have tracked this down to the **jdk.security.jgss** module not being present in Burp's OpenJDK JRE, and reported this to Portswigger. As it says in the updated README, Berserko should work if Burp is launched with a full JRE rather than the bundled version.

**Comment by rtt-ncc** [comment]
Fixed in Burp v2020.5.1.
Closing this issue.

**Comment by bshr** [comment]
Thanks!
